# Generated by Django 5.1.6 on 2025-03-02 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contactID", models.CharField(blank=True, max_length=30)),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=30)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("email", models.CharField(blank=True, max_length=30)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("color", models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskID", models.CharField(blank=True, max_length=30)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("category", models.CharField(blank=True, max_length=33)),
                ("currentProgress", models.IntegerField(default=0)),
                ("description", models.TextField()),
                ("dueDate", models.CharField(blank=True, max_length=30)),
                ("priority", models.CharField(default="", max_length=30)),
                ("color", models.CharField(default="", max_length=30)),
                (
                    "assignedTo",
                    models.ManyToManyField(
                        blank=True, related_name="contacts", to="join_api_app.contact"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subtasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subTaskID", models.CharField(blank=True, max_length=30)),
                ("subTaskName", models.CharField(max_length=512)),
                ("done", models.BooleanField(default=False)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="join_api_app.tasks",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userId", models.CharField(blank=True, max_length=30)),
                (
                    "userData",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="join_api_app.contact",
                    ),
                ),
            ],
        ),
    ]
