# Generated by Django 5.1.6 on 2025-03-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("join_api_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="category",
            field=models.CharField(
                choices=[
                    ("technicalTask", "Technical Task"),
                    ("userStory", "User Story"),
                    ("bug", "Bug"),
                    ("feature", "Feature"),
                    ("refactor", "Refactor"),
                    ("documentation", "Documentation"),
                    ("Testing", "Testing QA"),
                    ("Analysis", "Analysis/Research"),
                    ("design", "Design"),
                    ("noCategory", "No Category"),
                ],
                default="technicalTask",
                max_length=33,
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="color",
            field=models.CharField(default="#000000", max_length=7),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("urgent", "Urgent")],
                default="medium",
                max_length=10,
            ),
        ),
    ]
