# Generated by Django 5.1.6 on 2025-03-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("join_api_app", "0002_alter_tasks_category_alter_tasks_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="initials",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
    ]
