# Generated by Django 5.1.6 on 2025-03-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("join_api_app", "0005_alter_contact_first_name_alter_contact_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subtasks",
            name="task",
        ),
        migrations.RemoveField(
            model_name="users",
            name="userData",
        ),
        migrations.AddField(
            model_name="tasks",
            name="subtasks",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="assignedTo",
        ),
        migrations.DeleteModel(
            name="ContactList",
        ),
        migrations.AddField(
            model_name="tasks",
            name="assignedTo",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
