# Generated by Django 5.1.6 on 2025-03-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("join_api_app", "0006_remove_subtasks_task_remove_users_userdata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="assignedTo",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subtasks",
            field=models.TextField(default=""),
        ),
    ]
