# Generated by Django 5.1.6 on 2025-03-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("join_api_app", "0007_alter_tasks_assignedto_alter_tasks_subtasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="assignedTo",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subtasks",
            field=models.JSONField(default=list),
        ),
    ]
