# Generated by Django 5.1.6 on 2025-03-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("join_api_app", "0008_alter_tasks_assignedto_alter_tasks_subtasks"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummaryDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskInBoard", models.IntegerField(default=0)),
                ("taskInToDo", models.IntegerField(default=0)),
                ("taskInDone", models.IntegerField(default=0)),
                ("taskInProgress", models.IntegerField(default=0)),
                ("taskInFeedback", models.IntegerField(default=0)),
                ("urgendTaskUpcoming", models.JSONField(default=list)),
            ],
        ),
    ]
