# Generated by Django 5.1.6 on 2025-03-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("join_api_app", "0009_summarydetails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="last_name",
        ),
    ]
